---

- import_tasks: sonar.yml
  tags: sonar
  when: operation == 'install' and ansible_facts['os_family'] == 'Debian'

- import_tasks: uninstall-sonar.yml
  tags: sonar
  when: operation == 'un-install' and ansible_facts['os_family'] == 'Debian'
