---

- import_tasks: gradle.yml
  tags: gradle
  when: operation == 'install' and ansible_facts['os_family'] == 'Debian'

- import_tasks: uninstall-gradle.yml
  tags: gradle
  when: operation == 'un-install' and ansible_facts['os_family'] == 'Debian'
