---

- name: "Installing Java"
  apt: pkg=openjdk-8-jdk state=present
  become: yes
  become_method: sudo

# Setzen Sie PATH environment variable mit neue jdk
- name: "Einfügen Sie JAVA_HOME in ~/.bashrc"
  lineinfile:
    path: ~/.bashrc
    regexp: '^JAVA_HOME'
    line: "JAVA_HOME={{java_home}}"
    backup: yes
    insertafter: EOF

- name: "Einfügen Sie PATH in ~/.bashrc"
  lineinfile:
    path: ~/.bashrc
    regexp: '^PATH=\$JAVA_HOME/bin:\$PATH'
    line: "PATH=$JAVA_HOME/bin:$PATH"
    insertafter: EOF
  notify:
    - load environment