---

- name: "Löschen Sie PATH von ~/.bashrc"
  lineinfile:
    path: ~/.bashrc
    regexp: '^PATH=\$JAVA_HOME/bin:\$PATH'
    state: absent

- name: "Löschen Sie JAVA_HOME von ~/.bashrc"
  lineinfile:
    path: ~/.bashrc
    regexp: '^JAVA_HOME'
    state: absent
    backup: yes
  notify:
    - load environment

- name: "Un Installing Java"
  apt:
    pkg:
    - openjdk-8-jdk
    - openjdk-8-jdk-headless
    - openjdk-8-jre
    - openjdk-8-jre-headless
    state: absent
  become: yes
  become_method: sudo
