# -*- mode: ruby -*-
# vi: set ft=ruby :

N = 3
IMAGE_NAME = "ubuntu/xenial64"
Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
     # Display the VirtualBox GUI when booting the machine
     vb.gui = true

     # Customize the amount of memory on the VM:
     vb.memory = "2048"
     vb.cpus = 2
  end

  ANSIBLE_RAW_SSH_ARGS = []
  VAGRANT_VM_PROVIDER = "virtualbox"
  (1..N-1).each do |machine_id|
    ANSIBLE_RAW_SSH_ARGS << "-o IdentityFile=.vagrant/machines/kube-node-#{machine_id}/#{VAGRANT_VM_PROVIDER}/private_key"
  end

  (1..N).each do |i|
    config.vm.define "kube-node-#{i}" do |node|
        node.vm.box = IMAGE_NAME
        node.vm.network "private_network", ip: "192.168.50.#{i + 10}"
        if i == 1
            node.vm.hostname = "kubernetes-master"
        else
            node.vm.hostname = "kubernetes-node#{i}"
        end

        if i == N
            # Set up user and directories on all nodes
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "../admin-playbook.yml"
                ansible.limit = "administration"
                ansible.inventory_path = "../inventories/vagrant"
                ansible.extra_vars = {
                    operation: "setup",
                }
                ansible.tags = ["user"]
                ansible.ask_vault_pass = true
                ansible.raw_ssh_args = ANSIBLE_RAW_SSH_ARGS
            end

            # Install basic softwares on all nodes
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "../mandatory-softwares-playbook.yml"
                ansible.limit = "softwares"
                ansible.inventory_path = "../inventories/vagrant"
                ansible.extra_vars = {
                    operation: "install",
                    ansible_user: "raman",
                }
                ansible.tags = ["vim","dnsutils","git","java","docker", "einwohner", "config-server"]
                ansible.ask_vault_pass = true
                ansible.ask_become_pass = true
            end

            # Install and configure kubernetes master node
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "../kube-master-softwares-playbook.yml"
                ansible.limit = "kube_master"
                ansible.inventory_path = "../inventories/vagrant"
                ansible.extra_vars = {
                    operation: "install",
                    ansible_user: "raman",
                    node_ip: "192.168.50.11",
                }
                ansible.tags = ["kube-master"]
                ansible.ask_become_pass = true
            end

            # Install and configure normal kubernetes nodes
            node.vm.provision "ansible" do |ansible|
                ansible.playbook = "../kube-node-softwares-playbook.yml"
                ansible.limit = "kube_nodes"
                ansible.inventory_path = "../inventories/vagrant"
                ansible.extra_vars = {
                    operation: "install",
                    ansible_user: "raman",
                }
                ansible.tags = ["kube-node"]
                ansible.ask_become_pass = true
            end
        end
    end
  end
end
