---

# Step 1: Erstellen wir app directory, wenn nicht da
- name: "Erstellt Configuration Directory, wenn nicht da"
  file:
    path: "{{app_conf_home}}"
    mode: 0777
    owner: "{{user_name}}"
    group: "{{group_name}}"
    state: directory

- name: "Erstellt logs Directory, wenn nicht da"
  file:
    path: "{{app_logs_home}}"
    mode: 0777
    owner: "{{user_name}}"
    group: "{{group_name}}"
    state: directory

- name: "Erstellt einwohner Directory, wenn nicht da"
  file:
    path: "{{apps_directory}}/einwohner"
    mode: 0777
    owner: "{{user_name}}"
    group: "{{group_name}}"
    state: directory

# Step 2: Copy Certifikat und keystore
# Step 3: Executing templates und copy neue file
- name: Create config-server.properties.tpl
  template: src=config-server.properties.tpl dest="{{app_conf_home}}/config-server.properties" mode=0666
