---

- name: "Loeschen wir einwohner app-conf directory von system"
  file:
   path: "{{app_conf_home}}"
   state: absent

- name: "Loeschen wir einwohner app-logs directory von system"
  file:
    path: "{{app_logs_home}}"
    state: absent
