---
# Followed below web page to setup role steps
# https://www.elastic.co/guide/en/elastic-stack-get-started/6.7/get-started-elastic-stack.html
# http://localhost:5601/app/kibana#/dashboard/Metricbeat-system-overview
- name: "Elastic Search extrahieren"
  unarchive:
    src: "{{herunterladen_elasticsearch_url}}"
    dest: "{{servers_directory}}"
    remote_src: yes
    group: "{{group_name}}"
    owner: "{{user_name}}"
    mode: 0744
    creates: "{{elasticsearch_home}}"
    validate_certs: yes

- name: Create Elasticsearch startup script
  template: src=elasticsearch.tpl dest="{{elasticsearch_home}}/bin/elasticsearch-init" mode=0755

- name: Create link to access Elasticsearch
  file:
    src: "{{elasticsearch_home}}/bin/elasticsearch-init"
    dest: /usr/bin/elasticsearch
    state: link
  become: yes

- name: "Start Elasticsearch"
  shell: "/usr/bin/elasticsearch start"
  become: yes

- name: "wait for elastic search to start"
  wait_for: port={{elasticsearch_port}}

# Install Kibana
- name: "Kibana Archiv extrahieren"
  unarchive:
    src: "{{herunterladen_kibana_url}}"
    dest: "{{servers_directory}}"
    remote_src: yes
    group: "{{group_name}}"
    owner: "{{user_name}}"
    mode: 0744
    creates: "{{kibana_home}}"
    validate_certs: yes

- name: Create Kibana startup script
  template: src=kibana.tpl dest="{{kibana_home}}/bin/kibana-init" mode=0755

- name: Create link to access Kibana
  file:
    src: "{{kibana_home}}/bin/kibana-init"
    dest: /usr/bin/kibana
    state: link
  become: yes

- name: "Start kibana"
  shell: "/usr/bin/kibana start"
  become: yes

- name: "wait for Kibana to start"
  wait_for: port={{kibana_port}}

# Install logstash
- name: "Logstash Archiv extrahieren"
  unarchive:
    src: "{{herunterladen_logstash_url}}"
    dest: "{{servers_directory}}"
    remote_src: yes
    group: "{{group_name}}"
    owner: "{{user_name}}"
    mode: 0744
    creates: "{{logstash_home}}"
    validate_certs: yes

- name: Create logstash startup script
  template: src=logstash.tpl dest="{{logstash_home}}/bin/logstash-init" mode=0755

- name: Create link to access Logstash
  file:
    src: "{{logstash_home}}/bin/logstash-init"
    dest: /usr/bin/logstash
    state: link
  become: yes

# Install Filebeat
- name: "Filebeat Archiv extrahieren"
  unarchive:
    src: "{{herunterladen_filebeat_url}}"
    dest: "{{servers_directory}}"
    remote_src: yes
    group: "{{group_name}}"
    owner: "{{user_name}}"
    mode: 0744
    creates: "{{filebeat_home}}"
    validate_certs: yes

- name: Create Filebeat startup script
  template: src=filebeat.tpl dest="{{filebeat_home}}/filebeat-init" mode=0755

- name: Create link to access Filebeat
  file:
   src: "{{filebeat_home}}/filebeat-init"
   dest: /usr/bin/filebeat
   state: link
  become: yes

# Install Metricbeat
- name: "Install Metricbeat"
  apt:
    deb: "{{herunterladen_metricbeat_url}}"
  become: yes

- name: "From the Metricbeat install directory, enable the system module"
  shell: metricbeat modules enable system
  become: yes

- name: "Set up the initial environment"
  shell: metricbeat setup -e
  become: yes

- name: Start Metricbeat
  service: name=metricbeat state=started daemon_reload=yes
  become: yes
