---

#- name: Stop Metricbeat
#  service: name=metricbeat state=stopped
#  become: yes

- name: "Remove Metricbeat"
  apt:
    name: metricbeat
    purge: yes
    state: absent
  become: yes

# Despite the script available in path, it is not executing. Will see later
- name: "Stop Logsash"
  shell: 'usr/bin/logstash stop'
  become: yes

- name: "Removing link of logstash from /usr/bin"
  file:
    path: /usr/bin/logstash
    state: absent
  become: yes

- name: "Stop Filebeat"
  shell: '/usr/bin/filebeat stop'
  become: yes

- name: "Removing link of filebeat from /usr/bin"
  file:
    path: /usr/bin/filebeat
    state: absent
  become: yes

- name: "Stop kibana"
  shell: '/usr/bin/kibana stop'
  become: yes

- name: "Removing link of kibana from /usr/bin"
  file:
    path: /usr/bin/kibana
    state: absent
  become: yes

- name: "Stop Elasticsearch"
  shell: '/usr/bin/elasticsearch stop'
  become: yes

- name: "Removing link of Elasticsearch from /usr/bin"
  file:
    path: /usr/bin/elasticsearch
    state: absent
  become: yes

- name: "Removing kibana_home from system"
  file:
    path: "{{kibana_home}}"
    state: absent

- name: "Removing elasticsearch_home from system"
  file:
    path: "{{elasticsearch_home}}"
    state: absent

- name: "Removing logstash_home from system"
  file:
    path: "{{logstash_home}}"
    state: absent

- name: "Removing filebeat_home from system"
  file:
    path: "{{filebeat_home}}"
    state: absent
