apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-logs
spec:
  # It means volume will be mounted for read and write mode on a single node
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  capacity:
    storage: 1Gi
  hostPath:
    path: /home/raman/programs/servers/app-logs
    type: Directory

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-logs
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi