---

# Step 1: Erstellen wir app directory, wenn nicht da
- name: "Erstellt Logs Directory, wenn nicht da"
  file:
    path: "{{host_config_server_logs_dir}}"
    mode: 0777
    owner: "{{user_name}}"
    group: "{{group_name}}"
    state: directory

- name: "Erstellt config-server Directory, wenn nicht da"
  file:
    path: "{{apps_directory}}/config-server"
    mode: 0777
    owner: "{{user_name}}"
    group: "{{group_name}}"
    state: directory
