---
- name: "Loeschen wir config server app-logs directory von system"
  file:
    path: "{{host_config_server_logs_dir}}"
    state: absent

- name: "Loeschen wir einwohner apps_directory/config-server directory von system"
  file:
    path: "{{apps_directory}}/config-server"
    state: absent
