---
# Here we are ignoring any error came while invoking the command, and assume that software / Tool is not installed
- name: Verify Docker
  shell: docker --version
  register: docker_version_command
  become: yes
  become_method: sudo
  ignore_errors: True

- name: Verify Docker compose
  shell: docker-compose --version | cut -d ' ' -f3,4,5
  register: docker_compose_version_command
  become: yes
  become_method: sudo
  ignore_errors: True

- name: Verify Docker machine
  shell: docker-machine version | cut -d ' ' -f3,4,5
  register: docker_machine_version_command
  become: yes
  become_method: sudo
  ignore_errors: True
