---
# Tags can be used to execute a specific task e.g. ansible-playbook -i inventories/staging site.yml --tags dnsutils --ask-sudo-pass --extra-vars "operation=install"
# Here the task execution will be dependent upon operation i.e. if operation is install, install task will be executed and another one will be skipped

- name: "Installing DnsUtils"
  apt: pkg=dnsutils state=present
  become: yes
  become_method: sudo
