---

- name: Update the apt package index Ubuntu
  apt:
   update_cache: yes
  become: yes

- name: Install packages to allow apt to use a repository over HTTPS Ubuntu
  apt:
   name: "{{ packages }}"
   update_cache: yes
  vars:
   packages:
   - apt-transport-https
   - ca-certificates
   - curl
   - gnupg-agent
   - software-properties-common
  become: yes

- name: Add Docker’s official GPG key Ubuntu
  apt_key:
   url: "{{docker_gpg_key_url}}"
   state: present
  become: yes

- name:  Set up the stable repository Ubuntu
  apt_repository:
   repo: "{{docker_repo}}"
   state: present
  become: yes

- name: Install Docker on Ubuntu
  apt:
   name: "{{ packages }}"
   update_cache: yes
  vars:
   packages:
   - docker-ce
   - docker-ce-cli
   - containerd.io
  become: yes
