---
# Use shell command if apt package does not work shell: apt-get -y purge docker-ce
- name: Uninstall Docker CE package
  apt:
   name: docker-ce
   state: absent
  become: yes
  become_method: sudo

- name: Remove images and containers
  file:
    path: /var/lib/docker
    state: absent
  become: yes
  become_method: sudo
