---
# Use shell command if apt package does not work shell: apt-get -y purge docker-ce
- name: Loeschen Sie docker-machine Symbolic link
  file:
    path: /usr/bin/docker-machine
    state: absent
  become: yes

- name: Loeschen Sie docker-machine
  file:
    path: "{{programs_location}}/docker-machine"
    state: absent

- name: Loeschen Sie docker-compose Symbolic link
  file:
   path: /usr/bin/docker-compose
   state: absent
  become: yes

- name: Loeschen Sie docker-compose
  file:
   path: "{{programs_location}}/docker-compose"
   state: absent

- name: Uninstall Docker CE package
  apt:
   name: docker-ce
   state: absent
  become: yes
  become_method: sudo

- name: Remove images and containers
  file:
    path: /var/lib/docker
    state: absent
  become: yes
  become_method: sudo
